version: "3.8"


services:
  library_database:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    volumes:
      - library-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  library-postgres-data: